### ISSUE TITLE
Example setup for usage with postcss-devtools

### ISSUE THREAD

**Issue by export-mike** [postcss/postcss-devtools#17]
How to set up in a webpack config.

ref: https://github.com/postcss/postcss-loader/issues/73

**Comment by ai** [comment]
What did you already tried and what problem did you have?

**Comment by export-mike** [comment]
![image](https://cloud.githubusercontent.com/assets/2983327/15707817/b30b84ce-27f2-11e6-8b5d-2930fe65e8ca.png)
I'm a webpack user been folllowing https://github.com/webpack/css-loader/issues/124#issuecomment-204193809 … can't figure out the loader configuration.

**Comment by export-mike** [comment]
do I just do `!postcss-devtools`?

**Comment by ai** [comment]
You should read postcss-loader API more careful 😉.

You need to describe PostCSS plugins in special section of `webpack.config.js`. Look for examples in main section of postcss-loader README.md

**Comment by ai** [comment]
You should put devtools only once. Before other plugins.

[devtools(), plugin1, plugin2, plugin3]

**Comment by ai** [comment]
Also postcss section in webpack config should return this plugins array.

**Comment by export-mike** [comment]
thanks this works.

I'm using css-modules and from css-loader so this loads up multiple css files for a given build I wonder if theres a way to get an aggregate report on the results for a build? as I'm seeing metrics on different postcss plugins per css file. 

I have too many to individually count through.

Ideally the same output but the sum of a stylesheets.

**Comment by ai** [comment]
Sorry, there is no such way. Maybe you should create a issue in devtools for this feature?

**Comment by export-mike** [comment]
done: https://github.com/postcss/postcss-devtools/issues/18

**Comment by Benno007** [comment]
So would this be an accurate way of using your tool in webpack?
```
var devtools = require('postcss-devtools');
module.exports = {
    plugins: [
        devtools({
            precise: true,
            silent: false
        }),
        // allows us to set up and use application wide themes
        // @see https://github.com/andywer/postcss-theme
        theme({ themePath: themePath }),

        // our custom traits plugin to handle css module composing
        traits({ traitsPath: baseTraitsPath }),

        // plugin to add :focus selector to every :hover for keyboard accessibility.
        postcssFocus(),

        // PostCSS-cssnext is a PostCSS plugin that allows us to use the latest CSS syntax.
        // It transforms CSS specs into more compatible CSS so you don’t need to wait for browser support.
        cssnext({
            browsers: ['last 2 versions', 'IE > 10']
        }),

        // console.log() the messages (warnings, etc.) registered by other PostCSS plugins.
        postcssReporter({

            // sIf true, the plugin will clear the result's messages after it logs them.
        })
    ]
};
```

**Comment by export-mike** [comment]
@Benno007 Yes that looks correct
