### ISSUE TITLE
TypeError: Cannot read property 's' of undefined

### ISSUE THREAD

**Issue by maraisr** [postcss/postcss-devtools#32]
`postcss-devtools/dist/lib/formatter.js:29:33` has an issue.. 

```
devtools: v1.1.0
postcss: v5.1.1 (under gulp-postcss v 6.1.1)
```

Plugins:
`postcss-devtools`
`postcss-position`
`lost`
`autoprefixer`
`css-mqpacker`
`cssnano`
`postcss-sorting` (with `cssortie`)

Happy to provide more if need be.

**Comment by ben-eb** [comment]
Hi, sorry for the delay. 😄 

I think this was caused by the plugin trying to format messages that were not created by it, so they didn't have a `time` property. I've fixed this now and released version `1.1.1`.

Hope this helps!
